name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install yarn packages
      run: yarn
    - name: run the tests
      run: yarn test
